[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = [{ name = "Cristopher" }]
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.0",
    "hyundai-kia-connect-api>=3.32.7",
]
